# Generated by Django 3.0.8 on 2020-07-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
